name: 请求功能
description: 对shokaX的建议或功能请求
labels: ["enhancement ✨"]
body:
  - type: "markdown"
    attributes:
      value: |
        标题请简要描述功能
  - type: checkboxes
    id: beforeraise
    attributes:
      label: 在开始之前......
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
          required: true
        - label: 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个建议"、"加功能"等
          required: true
        - label: 我确认最新版尚未添加此功能，且此前没有人提出过此问题
          required: true
        - label: 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`
          required: true
  - type: "textarea"
    id: describe
    attributes:
      label: 建议描述
      description: |
        详细描述建议,如有参考链接可粘贴于此
    validations:
      required: true
  - type: checkboxes
    id: checkagain
    attributes:
      label: 注意事项
      description: |
        1. 请确认此功能未与现有请求重复
      options:
        - label: 我已确认以上事项
          required: true
