name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install pnpm -g

      - name: Build TypeScript files
        run: |
          pnpm install
          echo "NO_DEPS_HOIST=true" >> $GITHUB_ENV
          pnpm run build

      - run: npm publish
        if: "!github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - run: npm publish --tag dev
        if: "github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
